// Every Material Symbols glyph the site renders. The Google Fonts request
// asks for exactly these (icon_names), so a glyph missing here would render
// as its ligature text; Icon.svelte types its `name` prop against this list
// to stop that at compile time.
export const ICONS = [
  'account_tree',
  'add',
  'arrow_drop_down',
  'arrow_forward',
  'arrow_outward',
  'arrow_selector_tool',
  'bolt',
  'check',
  'check_circle',
  'close',
  'code',
  'content_copy',
  'content_cut',
  'data_object',
  'deployed_code',
  'description',
  'desktop_windows',
  'download',
  'error',
  'filter_list',
  'fit_screen',
  'folder',
  'folder_open',
  'function',
  'history',
  'http',
  'info',
  'key',
  'lan',
  'laps',
  'laptop_mac',
  'link',
  'lock',
  'lock_open',
  'menu',
  'more_vert',
  'play_arrow',
  'public',
  'remove',
  'rss_feed',
  'schedule',
  'search',
  'shield',
  'sticky_note_2',
  'stop',
  'swap_horiz',
  'terminal',
  'timer',
  'upload_file',
  'verified_user',
  'warning',
] as const

export type IconName = (typeof ICONS)[number]
