// Regenerates the light-theme palette block in src/style.css from Tailwind's
// default theme. Components are written against the dark palette, so the
// light theme mirrors it: every neutral shade becomes its opposite (950 ↔ 50,
// 900 ↔ 100, …), accent text tints darken the same way, and the solid 500/600
// accent fills that buttons and badges use both land on 600 so they stay
// readable under white text. Run with: bun run scripts/light-theme.ts
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const THEME_CSS = `${ROOT}node_modules/tailwindcss/theme.css`
const STYLE_CSS = `${ROOT}src/style.css`
const START_MARKER = '    /* light-palette:start (generated by scripts/light-theme.ts) */'
const END_MARKER = '    /* light-palette:end */'

const FAMILIES = ['zinc', 'emerald', 'rose', 'violet', 'sky', 'amber', 'red', 'orange', 'cyan'] as const
const NEUTRAL_FAMILY = 'zinc'
const SHADE_SUM = 1000
const SOLID_SHADES = new Set([500, 600])
const SOLID_LIGHT_SHADE = 600

type Family = (typeof FAMILIES)[number]

function lightShade(family: Family, shade: number): number {
  if (family !== NEUTRAL_FAMILY && SOLID_SHADES.has(shade)) return SOLID_LIGHT_SHADE
  return SHADE_SUM - shade
}

function readPalette(): Map<string, string> {
  const palette = new Map<string, string>()
  const pattern = /^\s*--color-([a-z]+)-(\d+):\s*([^;]+);/
  for (const line of readFileSync(THEME_CSS, 'utf8').split('\n')) {
    const match = pattern.exec(line)
    if (match) palette.set(`${match[1]}-${match[2]}`, match[3].trim())
  }
  return palette
}

function generate(palette: Map<string, string>): string[] {
  const lines: string[] = []
  for (const family of FAMILIES) {
    const shades = [...palette.keys()]
      .filter((key) => key.startsWith(`${family}-`))
      .map((key) => Number(key.slice(family.length + 1)))
      .sort((a, b) => a - b)
    for (const shade of shades) {
      const value = palette.get(`${family}-${lightShade(family, shade)}`)
      if (!value) throw new Error(`no ${family} shade for ${shade}`)
      lines.push(`    --color-${family}-${shade}: ${value};`)
    }
  }
  return lines
}

const style = readFileSync(STYLE_CSS, 'utf8')
const start = style.indexOf(START_MARKER)
const end = style.indexOf(END_MARKER)
if (start < 0 || end < 0) throw new Error('light-palette markers missing from src/style.css')
const block = [START_MARKER, ...generate(readPalette()), END_MARKER].join('\n')
writeFileSync(STYLE_CSS, style.slice(0, start) + block + style.slice(end + END_MARKER.length))
console.log('light palette regenerated')
