// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SaveBoard(arg1, arg2) {
  return window['go']['main']['App']['SaveBoard'](arg1, arg2);
}
