// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function CopyBoardJSON(arg1:string,arg2:string):Promise<void>;

export function CopySelection(arg1:string,arg2:store.Board,arg3:Array<string>):Promise<void>;

export function CreateProject(arg1:string):Promise<store.ProjectInfo>;

export function DeleteCollection(arg1:string,arg2:string):Promise<void>;

export function DeleteCredential(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExportBoardToFile(arg1:string,arg2:string):Promise<string>;

export function ImportBoardFromFile(arg1:string):Promise<main.ImportBoardResult>;

export function ListProjects():Promise<Array<store.ProjectInfo>>;

export function OpenProject(arg1:string):Promise<main.ProjectBundle>;

export function ReadClipboardEnvelope():Promise<main.ClipboardEnvelope>;

export function RenameProject(arg1:string,arg2:string):Promise<store.ProjectInfo>;

export function RunTransformScript(arg1:main.ScriptRunRequest):Promise<any>;

export function SaveBoard(arg1:string,arg2:store.Board):Promise<void>;

export function SaveCollection(arg1:string,arg2:store.Collection):Promise<void>;

export function SaveCredentials(arg1:string,arg2:Array<store.Credential>):Promise<void>;

export function SaveEnvironments(arg1:string,arg2:Array<store.Environment>):Promise<void>;

export function SendTestRequest(arg1:string,arg2:main.TestRequest):Promise<main.TestResponse>;

export function SetCredentialSecret(arg1:string,arg2:string,arg3:string):Promise<void>;
