// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyBoardJSON(arg1, arg2) {
  return window['go']['main']['App']['CopyBoardJSON'](arg1, arg2);
}

export function CopySelection(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopySelection'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteCollection(arg1, arg2) {
  return window['go']['main']['App']['DeleteCollection'](arg1, arg2);
}

export function DeleteCredential(arg1, arg2) {
  return window['go']['main']['App']['DeleteCredential'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportBoardToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportBoardToFile'](arg1, arg2);
}

export function ImportBoardFromFile(arg1) {
  return window['go']['main']['App']['ImportBoardFromFile'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ReadClipboardEnvelope() {
  return window['go']['main']['App']['ReadClipboardEnvelope']();
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function RunBoard(arg1, arg2) {
  return window['go']['main']['App']['RunBoard'](arg1, arg2);
}

export function RunTransformScript(arg1) {
  return window['go']['main']['App']['RunTransformScript'](arg1);
}

export function SaveBoard(arg1, arg2) {
  return window['go']['main']['App']['SaveBoard'](arg1, arg2);
}

export function SaveCollection(arg1, arg2) {
  return window['go']['main']['App']['SaveCollection'](arg1, arg2);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function SaveEnvironments(arg1, arg2) {
  return window['go']['main']['App']['SaveEnvironments'](arg1, arg2);
}

export function SendTestRequest(arg1, arg2) {
  return window['go']['main']['App']['SendTestRequest'](arg1, arg2);
}

export function SetCredentialSecret(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCredentialSecret'](arg1, arg2, arg3);
}

export function SetProjectDefaults(arg1, arg2) {
  return window['go']['main']['App']['SetProjectDefaults'](arg1, arg2);
}

export function StopRun(arg1) {
  return window['go']['main']['App']['StopRun'](arg1);
}
